import type { Metadata } from "next";
import localFont from "next/font/local";

import sitebg from '@/public/image/brandi-redd-aJTiW00qqtI-unsplash.jpg';

import "@/public/styles/globals.css";
import { Providers } from './providers';
import { AuthProvider } from "@/contexts/AuthContext";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const appFont = localFont({
  src: './fonts/woff2/IRANSansWeb_Light.woff2',
  // variable: '--font-iran-sans', // متغیر CSS برای فونت
})


export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode }>) {



  return (
    <html lang="fa" dir="rtl">
      <body
        className={`${appFont.className} `}
        style={{
          backgroundImage: `radial-gradient(1200px 600px at 80% -10%, rgba(124, 58, 237, 0.25), transparent 60%), radial-gradient(1000px 500px at 10% 110%, rgba(147, 51, 234, 0.2), transparent 60%)`,
          backgroundColor: '#0b0713',
          backgroundAttachment: 'fixed',
          position: "relative"
        }}>
        <AuthProvider>
          <Providers>
            {children}
          </Providers>
        </AuthProvider>
      </body>
    </html>
  );
}
