import type { Metadata } from "next";
import localFont from "next/font/local";

import sitebg from '@/public/image/brandi-redd-aJTiW00qqtI-unsplash.jpg';

import "@/public/styles/globals.css";
import { Providers } from './providers';
import { AuthProvider } from "@/contexts/AuthContext";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const appFont = localFont({
  src: './fonts/woff2/IRANSansWeb_Light.woff2',
  // variable: '--font-iran-sans', // متغیر CSS برای فونت
})


export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode }>) {



  return (
    <html lang="fa" dir="rtl">
      <body
        className={`${appFont.className} `}
        style={{
          backgroundImage: `url(${sitebg.src})`,
          backgroundSize: 'cover',
          backgroundPosition: 'center',
          backgroundAttachment: 'fixed',
          position: "relative"
        }}>
        <AuthProvider>
          <Providers>
            {children}
          </Providers>
        </AuthProvider>
      </body>
    </html>
  );
}
