import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer_homepage from "@/components/layouts/footer/Footer_homepage";
import Appbar from "@/components/layouts/appbar/Appbar";

import jungle from "@/public/backgrounds/jungle.jpg"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode }>) {




  return (
    <html lang="fa" dir="rtl">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>

        {/* اپبار سایت */}
        <Appbar />

        <div
          style={{
            minHeight: "calc(100vh - 200px)",
            backgroundImage: `url(${jungle.src})`,
            backgroundSize: "cover",
            backgroundPosition: "center",
            backgroundRepeat: "no-repeat",
            backgroundAttachment: "fixed",
            backgroundColor: "rgba(0, 0, 0, 0.5)",
            backgroundBlendMode: "overlay",
            position: "relative", // فعال کن!
          }}
        >
          <div
            style={{
              position: "absolute",
              inset: 0,
              backgroundColor: "rgba(255, 255, 255, 0.3)",
              backdropFilter: "blur(7px)",
              WebkitBackdropFilter: "blur(1px)", // برای پشتیبانی بهتر
              zIndex: 1,
            }}
          />
          <div style={{ position: "relative", zIndex: 2 }}>
            {children}
          </div>
        </div>

        {/* فوتر سایت */}
        <Footer_homepage />
      </body>
    </html>
  );
}
